# Generated by Django 5.2.7 on 2025-10-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitech', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
