# Generated by Django 5.2.7 on 2025-10-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitech', '0003_contactmessage_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Use FontAwesome icon class, e.g., fa-robot', max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
