# Generated by Django 5.2.7 on 2025-11-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitech', '0006_projectcategory_resultstatistic_portfolioproject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
